import 'package:flutter/material.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcrearcuentawidget/generated/GeneratedInput2Widget2.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcrearcuentawidget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcrearcuentawidget/generated/GeneratedCrearunacuentaWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcrearcuentawidget/generated/GeneratedFelcha1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcrearcuentawidget/generated/GeneratedContrasenaWidget1.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcrearcuentawidget/generated/GeneratedFondowindowsnegro1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcrearcuentawidget/generated/GeneratedCorreoWidget1.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcrearcuentawidget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcrearcuentawidget/generated/GeneratedEstasdeacuerdoconlosterminosycondicionesestablecidospor1.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcrearcuentawidget/generated/GeneratedSquareoutlineWidget1.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcrearcuentawidget/generated/GeneratedCorreoWidget2.dart';

/* Frame Crear Cuenta
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCrearCuentaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(178, 48, 211, 103),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedFondowindowsnegro1Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 203.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 490.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 40.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedSquareoutlineWidget1(),
              ),
              Positioned(
                left: 90.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 37.0,
                child: GeneratedCrearunacuentaWidget(),
              ),
              Positioned(
                left: 69.0,
                top: 529.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 40.0,
                child:
                    GeneratedEstasdeacuerdoconlosterminosycondicionesestablecidospor1(),
              ),
              Positioned(
                left: 127.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedInput2Widget2(),
              ),
              Positioned(
                left: 27.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedCorreoWidget1(),
              ),
              Positioned(
                left: 33.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedCorreoWidget2(),
              ),
              Positioned(
                left: 27.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedContrasenaWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 61.0,
                child: GeneratedFelcha1Widget(),
              )
            ]),
      ),
    ));
  }
}
