import 'package:flutter/material.dart';
import 'package:flutterapp/final_app_lehiapp/generatedloginwidget/generated/GeneratedCompuimg1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedloginwidget/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/final_app_lehiapp/generatedloginwidget/generated/GeneratedFondoalienverdeimg1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedloginwidget/generated/GeneratedLogopcshop2Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedloginwidget/generated/GeneratedBienvenidoaPCSHOPlatiendavirtualdeequipodecomputoqueofr.dart';
import 'package:flutterapp/final_app_lehiapp/generatedloginwidget/generated/GeneratedRectangle9Widget3.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(178, 48, 211, 103),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedRectangle9Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 1124.0,
                height: 915.0,
                child: GeneratedFondoalienverdeimg1Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 150.0,
                child: GeneratedLogopcshop2Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 202.0,
                child: GeneratedCompuimg1Widget(),
              ),
              Positioned(
                left: 132.0,
                top: 655.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup4Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 218.0,
                child:
                    GeneratedBienvenidoaPCSHOPlatiendavirtualdeequipodecomputoqueofr(),
              )
            ]),
      ),
    ));
  }
}
