import 'package:flutter/material.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedCorreoWidget3.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedFelcha2Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedSolicituddeempleoWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedCorreoWidget7.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedFondo21Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedCorreoWidget5.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedCorreoWidget6.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedRequisitosparaelempleodetecnicoenequipodecomputoWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedPolygon1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedCorreoWidget4.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/final_app_lehiapp/generatedsolicitudempleowidget/generated/GeneratedInput2Widget3.dart';

/* Frame Solicitud empleo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSolicitudempleoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(178, 48, 211, 103),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedRectangle9Widget2(),
              ),
              Positioned(
                left: -314.0,
                top: -121.0,
                right: null,
                bottom: null,
                width: 1300.0,
                height: 1083.0,
                child: GeneratedFondo21Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 757.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 30.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedCorreoWidget3(),
              ),
              Positioned(
                left: 27.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedCorreoWidget4(),
              ),
              Positioned(
                left: 23.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedCorreoWidget5(),
              ),
              Positioned(
                left: 56.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 181.0,
                child:
                    GeneratedRequisitosparaelempleodetecnicoenequipodecomputoWidget(),
              ),
              Positioned(
                left: 129.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedInput2Widget3(),
              ),
              Positioned(
                left: 23.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedCorreoWidget6(),
              ),
              Positioned(
                left: 28.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedCorreoWidget7(),
              ),
              Positioned(
                left: 327.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 29.0,
                child: GeneratedPolygon1Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 61.0,
                child: GeneratedFelcha2Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 47.0,
                child: GeneratedSolicituddeempleoWidget(),
              )
            ]),
      ),
    ));
  }
}
