import 'package:flutter/material.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedSillasWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedGroup5Widget1.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedFiltrarporpreciobottomWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedSillasWidget2.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedFelcha3Widget1.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedBuscasempleocomotecnicoTenemoscuposdisponiblesWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedCarrito1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedMuebleWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedPopularidadbottomWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedMonitor1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedGabinete1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedSillasWidget4.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedFelcha4Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedUnidaddvdexterna1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedTN4DuLKtA8QWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedCatalogoWidget3.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedSillasWidget1.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedDepartamentobottomWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedCategoriaWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedSillasWidget3.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedArrow1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedMouse1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedTeclado1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedBuhmhprfo3gWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedMemoriaram1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedcatalogowidget1/generated/GeneratedRectangle1Widget4.dart';

/* Frame Catalogo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCatalogoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(178, 48, 211, 103),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 822.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 12.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 180.0,
                child: GeneratedSillasWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 88.0,
                child: GeneratedMouse1Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 180.0,
                child: GeneratedSillasWidget1(),
              ),
              Positioned(
                left: 148.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 180.0,
                child: GeneratedSillasWidget2(),
              ),
              Positioned(
                left: 272.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 180.0,
                child: GeneratedMuebleWidget(),
              ),
              Positioned(
                left: 147.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 180.0,
                child: GeneratedSillasWidget3(),
              ),
              Positioned(
                left: 13.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 180.0,
                child: GeneratedSillasWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 36.0,
                child: GeneratedCategoriaWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 36.0,
                child: GeneratedPopularidadbottomWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 36.0,
                child: GeneratedDepartamentobottomWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 36.0,
                child: GeneratedFiltrarporpreciobottomWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 624.0,
                right: null,
                bottom: null,
                width: 108.51742553710938,
                height: 80.0,
                child: GeneratedBuhmhprfo3gWidget(),
              ),
              Positioned(
                left: 163.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 112.09317016601562,
                height: 80.0,
                child: GeneratedTN4DuLKtA8QWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 92.0,
                child: GeneratedGabinete1Widget(),
              ),
              Positioned(
                left: 145.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 107.0,
                child: GeneratedMonitor1Widget(),
              ),
              Positioned(
                left: 294.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 78.0,
                child: GeneratedMemoriaram1Widget(),
              ),
              Positioned(
                left: 133.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 88.0,
                child: GeneratedTeclado1Widget(),
              ),
              Positioned(
                left: 288.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 98.0,
                child: GeneratedUnidaddvdexterna1Widget(),
              ),
              Positioned(
                left: 124.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 63.0,
                child: GeneratedCatalogoWidget3(),
              ),
              Positioned(
                left: 294.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 80.0,
                child: GeneratedCarrito1Widget(),
              ),
              Positioned(
                left: -10.0,
                top: 697.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 181.0,
                child:
                    GeneratedBuscasempleocomotecnicoTenemoscuposdisponiblesWidget(),
              ),
              Positioned(
                left: 252.0,
                top: 826.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup5Widget1(),
              ),
              Positioned(
                left: 138.0,
                top: 847.0,
                right: null,
                bottom: null,
                width: 69.00724792480469,
                height: 0.0,
                child: GeneratedArrow1Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 61.0,
                child: GeneratedFelcha3Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 61.0,
                child: GeneratedFelcha4Widget(),
              )
            ]),
      ),
    ));
  }
}
