import 'package:flutter/material.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedImg2Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedEncuentralosmejorescomponentesparatuequipodecomputoWidg.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedFelcha5Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedInput2Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedBuscaarticulosdetunecesidadennuestrocatalogoWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedImg3Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedImg1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedInicioWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatedhomewidget/generated/GeneratedIniciasesionpararecibirlasalertasdenuestrosnuevasproduc.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(178, 48, 211, 103),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 790.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 160.0,
                child: GeneratedImg1Widget(),
              ),
              Positioned(
                left: 143.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 160.0,
                child: GeneratedImg2Widget(),
              ),
              Positioned(
                left: 277.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 160.0,
                child: GeneratedImg3Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 52.0,
                child:
                    GeneratedEncuentralosmejorescomponentesparatuequipodecomputoWidg(),
              ),
              Positioned(
                left: 84.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 68.0,
                child:
                    GeneratedIniciasesionpararecibirlasalertasdenuestrosnuevasproduc(),
              ),
              Positioned(
                left: 91.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 80.0,
                child:
                    GeneratedBuscaarticulosdetunecesidadennuestrocatalogoWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedInput2Widget(),
              ),
              Positioned(
                left: 229.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 229.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 139.0,
                top: 695.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 116.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 63.0,
                child: GeneratedInicioWidget(),
              ),
              Positioned(
                left: 6.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 61.0,
                child: GeneratedFelcha5Widget(),
              )
            ]),
      ),
    ));
  }
}
