import 'package:flutter/material.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedEstasdeacuerdoconlosterminosycondicionesestablecidospor.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedInput2Widget1.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedSquareoutlineWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedIniciarsesionWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedFondo31Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedContrasenaWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedCreaunacuentaWidget2.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedFelcha3Widget.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedTodavianotienescuentaWidget.dart';
import 'package:flutterapp/final_app_lehiapp/generatediniciodesesionwidget/generated/GeneratedCorreoWidget.dart';

/* Frame Inicio de sesion
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIniciodesesionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(178, 48, 211, 103),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedFondo31Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 378.0,
                height: 490.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 33.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedSquareoutlineWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 22.0,
                child: GeneratedTodavianotienescuentaWidget(),
              ),
              Positioned(
                left: 62.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 40.0,
                child:
                    GeneratedEstasdeacuerdoconlosterminosycondicionesestablecidospor(),
              ),
              Positioned(
                left: 252.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 20.0,
                child: GeneratedCreaunacuentaWidget2(),
              ),
              Positioned(
                left: 133.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedInput2Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedCorreoWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedContrasenaWidget(),
              ),
              Positioned(
                left: 115.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 37.0,
                child: GeneratedIniciarsesionWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 61.0,
                child: GeneratedFelcha3Widget(),
              )
            ]),
      ),
    ));
  }
}
